ARC-0003: Testnet 3.2
AleoHQ/ARCs pull request #15
Opened 2022-09-30 23:55 UTC by collinc97

## Abstract

The purpose of this ARC is to unify syntax between Leo and Aleo instructions to make it clear what tools developers have at their disposal. We propose several breaking changes to both Leo and Aleo instructions to achieve this goal.

Leo breaking changes:
* Add `program name.network {}` scope
* Add `interface` abstract type
* Change `circuit` type -> `struct` type
* Change `@program function` -> `transition`

Aleo instructions breaking changes:
* Add `interface` abstract type
* Change `interface` type -> `struct` type
* Change `function` -> `transition`
* Change `closure` -> `function`

2022-10-01 03:46 UTC, bendyarm requested changes
This is an improvement on the syntax for both Leo and Aleo Instructions!
I think a 3-column table would be better, to better show how the syntax is being standardized.
How about  this:


| Leo V1           —> | Leo V2 & Aleo Instructions V2 | <—  Aleo Instructions V1 |
|:-------------------:|:-----------------------------:|:------------------------:|
| ---                 | `program`                     | `program`                |
| ∅                   | `interface`                   | ∅                        |
| `mapping`           | `mapping`                     | `mapping`                |
| `circuit`           | `struct`                      | `interface`              |
| `record`            | `record`                      | `record`                 |
| `@program function` | `transition`                  | `function`               |
| `function`          | `function`                    | `closure`                |
| *name.network*      | *name.network*                | *name.network*           |

2022-10-03 17:27 UTC, collinc97 commented
> This is an improvement on the syntax for both Leo and Aleo Instructions! I think a 3-column table would be better, to better show how the syntax is being standardized. How about this:
> 
> Leo V1 —>	Leo V2 & Aleo Instructions V2	<— Aleo Instructions V1
> ---	`program`	`program`
> ∅	`interface`	∅
> `mapping`	`mapping`	`mapping`
> `circuit`	`struct`	`interface`
> `record`	`record`	`record`
> `@program function`	`transition`	`function`
> `function`	`function`	`closure`
> _name.network_	_name.network_	_name.network_

This is a great idea Eric. Making the change now!

2022-10-03 18:05 UTC, evanmarshall commented
Hi, just a couple questions about the new interface. 

1. Can a program implement multiple interfaces?

2. How will importing interfaces work? Is this planned to work with the Aleo Package Manager?

2022-10-03 22:13 UTC, howardwu commented
> Hi, just a couple questions about the new interface.
> 
> 1. Can a program implement multiple interfaces?
> 2. How will importing interfaces work? Is this planned to work with the Aleo Package Manager?

+1, I'm also still working through how to design interfaces, especially for Aleo instructions. Let's get this document merged and continue discussion on interfaces in the [Discussion](https://github.com/AleoHQ/ARCs/discussions/17) page.

2022-10-03 22:32 UTC, howardwu approved these changes

2022-10-04 00:10 UTC, bendyarm approved these changes
Looks good to me!
If we want to get away from "breaking changes"
we could say something like "changes from the previous prerelease version" but that doesn't seem too important to me.

2022-10-04 00:23 UTC, collinc97 commented
ARC-0003: Leo and Aleo instructions

> Looks good to me! If we want to get away from "breaking changes" we could say something like "changes from the previous prerelease version" but that doesn't seem too important to me.

We can still iterate on the document once it is living.

2022-10-04 00:23 UTC, merged